# Generated by Django 3.2.9 on 2021-11-20 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_sportsbook', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('nba', 'NBA'), ('nfl', 'NFL'), ('mma', 'MMA')], max_length=20),
        ),
    ]
