# Generated by Django 3.2.9 on 2021-11-21 05:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_sportsbook', '0003_auto_20211121_0205'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='away_team_points_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='event',
            name='home_team_points_scored',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
