# Generated by Django 3.2.9 on 2021-11-21 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_sportsbook', '0004_auto_20211121_0547'),
    ]

    operations = [
        migrations.AddField(
            model_name='betslip',
            name='predicted_outcome',
            field=models.CharField(blank=True, max_length=75, null=True),
        ),
        migrations.AddField(
            model_name='betslip',
            name='processed_ticket',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='betslip',
            name='type_of_bet',
            field=models.CharField(choices=[('money line', 'Money Line'), ('spread', 'Spread'), ('over under', 'Over Under')], default='money line', max_length=20),
        ),
    ]
