# Generated by Django 3.2.9 on 2021-12-01 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_sportsbook', '0005_auto_20211121_0811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('nba', 'NBA'), ('nfl', 'NFL'), ('mma', 'MMA'), ('custom', 'CUSTOM'), ('nhl', 'NHL'), ('ncaab', 'NCAAB')], max_length=20),
        ),
    ]
