# Generated by Django 4.0.3 on 2022-04-12 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('simulated_sportsbook', '0006_alter_event_sport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='sport',
            field=models.CharField(choices=[('nba', 'NBA'), ('nfl', 'NFL'), ('mma', 'MMA'), ('custom', 'CUSTOM'), ('nhl', 'NHL'), ('ncaab', 'NCAAB'), ('mlb', 'MLB')], max_length=20),
        ),
    ]
